name: racs-experiments
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - dill
  - pip:
    - mlflow>=1.0
    - matplotlib
    - "-e git+https://github.com/ParrotPrediction/pyalcs.git@db61bec258d00860bb089d319df6f9c6eb50439f#egg=parrotprediction-pyalcs"
    - "-e git+https://github.com/ParrotPrediction/openai-envs.git@89f25c592e6c1be07a98754560bc8ca2c89b4591#egg=parrotprediction-openai-envs"
